Add and remove features
aima98/To-Do-List pull request #2
Opened 2023-03-30 03:31 UTC by aima98

- Adding a new JavaScript file and import it as a module:
       1.  it will contain methods related to the status updates (completed: true / false).

- Adding event listener to the checkbox (change).
- Updating items object's value for completed key upon user actions.
- Implementing a function for the "Clear all completed" button (use filter() method).
- Storing the updated array of items in local storage, so the user gets the correct list of values after the page reloads (which means that any changes made to the list should be preserved).

2023-03-30 04:36 UTC, CollinsTatang requested changes
Hi @aima98, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

## Required changes 
It's ok to have bugs in your code. Please, see this code review as a chance for you to learn practical coding skills and learn new tips that can improve your code quality and help you get a better job.

- [ ] Kindly check your README file and correct the duplication of the `Show your support` section and remember the `Acknowledgments` is placed just above the `License` section according to the [README](https://github.com/microverseinc/readme-template) format.
![readme](https://user-images.githubusercontent.com/55596970/228730510-32b91cdf-bf0b-4cd9-8532-5dd6eedf4ec9.png)


_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 04:36 UTC, CollinsTatang commented on src/modules/Delete.js
> +export default deleteTask;
Hi @aima98 
You have done a great job implementing the different features of this app but there is a little update to complete the task.

- [ ] Please your app throws an error every time a user clicks the side button to delete a to-do in the list.
**Take A Look Blow**
![delete](https://user-images.githubusercontent.com/55596970/228727643-603eeeef-16cc-427f-a085-6269c0eb295b.png)
**Please fix the above error**

2023-03-30 16:21 UTC, Ibizugbe requested changes
Hi @aima98 👋👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/228900397-fdeaa963-c2fb-4cf8-957e-3b3b9c35fd3a.gif)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅

- [x] Github flow practice has been used👍
- [x] add function works properly👍


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [OPTIONAL] Some sections are missing in your readme😉 Kindly note that we are required to make use of the [microverse readme template](https://github.com/microverseinc/readme-template) for our projects and every section must be correctly filled except the FAQ section which is optional😉 Kindly ensure your readme is properly documented to give your prooject a more professional look😉😉👍

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 16:21 UTC, Ibizugbe commented on src/index.js
>    }
Nice job so far👍 But you still haven't completely implemented the changes requested by the previous reviewer🥲 Your app still has some issues when calling the remove function🥲 Kindly take a look at the video below for clarity to see the current behavior of your app and make the necessary change👍



https://user-images.githubusercontent.com/64643995/228900081-4b81b271-7efb-4788-98f2-837da1e80f8b.mp4

2023-03-31 01:19 UTC, Reem-lab reviewed
Hi @aima98, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that have a live demo section in your README file and to have a professional README file you should remove this section till you have your app deployed so you can just add the live demo section in case you have deployed link for your project is present. .✅❗💯🤩✨✨


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-31 02:00 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @aima98, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of GitHub flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 02:03 UTC, merged